name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v3.9.1

      - name: Install dependencies
        run: npm install

      - name: Build MalaCara APP
        run: npm run build:prod

      - name: Copy index.html to 404.html
        run: cp dist/MalaKara/browser/index.html dist/MalaKara/browser/404.html

      - name: Deploy Github pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          build_dir: dist/MalaKara/browser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
